# ui_constants.py
# Shared UI constants for internationalization and language support

UI_LABELS = {
    "en": {
        "general_tab": "General",
        "fast_tts": "Fast Text to Speech",
        "enable_autosave": "Enable Auto-Save",
        "show_random_quote": "Show Random Quotes",
        "language": "Language",
        "appearance_tab": "Appearance",
        "theme": "Theme",
        "background_color": "Background Color",
        "text_size": "Text Size",
        "provider_tab": "Providers",
        "provider": "Provider",
        "provider_info": "Provider Information",
        "endpoint_url": "Endpoint URL",
        "model": "Model",
        "api_key": "API Key",
        "timeout": "Timeout (seconds)",
        "test": "Test",
        "save": "Save",
        "close": "Close",
        "discard": "Discard",
        "cancel": "Cancel",
        "delete": "Delete",
        "choose": "Choose a provider...",
        "name": "Name",
        "default_provider": "Default Provider",
        "reveal": "Reveal",
        "hide": "Hide",
        "api_key_required": "API Key Required",
        "test_successful": "Connection successful!",
        "test_failed": "Connection failed: {}",
        "delete_confirmation": "Are you sure you want to delete the selected provider?",
        "delete_title": "Confirm Deletion",
        "new_provider": "New Provider",
        "edit_provider": "Edit Provider",
        "providers_list": "Configured Providers",
        "leave_empty": "Leave empty for default",
        "refresh_models": "Refresh Model List",
        "edit": "Edit",
        "provider_details": "Provider Details",
        "add": "Add",
        "update": "Update",
        "sample": "Sample Text",
        "save_successful": "Settings saved successfully.",
        "unsaved_warning": "You have unsaved changes. Do you want to save them before closing?",
        "endpoint_help_tooltip": "https://example.com/v1",
        "endpoint_help_title": "Endpoint URL Help",
        "endpoint_help_message": "Override URL for provider\n\nOnly use if you have a proxy server or a Custom provider.\nLeave empty for default URL.\n\nEx: 'https://localhost:1234/v1'",
        "provider_info_title": "Provider and Model Information",
        "filter": "Filter",
        "filter_all": "All Models",
        "filter_free": "Free Models",
        "filter_chat": "Chat Capabilities",
        "filter_research": "Research Capabilities",
        "filter_instruction": "Instruction Following",
        "model_details": "Model Details",
        "context_length": "Context Length",
        "pricing": "Pricing",
        "description": "Description",
        "architecture": "Architecture",
        "no_models": "No models available or error fetching models.",
        "group_by_provider": "Group by Provider",
        "group_by_category": "Group by Category",
    },
    # Add other languages as needed
}

LANGUAGES = ["en", "de", "es", "fr", "pt", "pl", "ru", "ja", "zh", "ko"]